### ISSUE TITLE
大佬试过不插独显运行么？

### ISSUE THREAD

**Issue by OptimusV5** [xiaojun996/Hackintosh-B460M-MORTAR-i5-10400-RX5700-4K#4]
想请教下，如果不插独显，只用核显，能正常开机使用各种功能么？

**Comment by zhixiangyao** [comment]
> 想请教下，如果不插独显，只用核显，能正常开机使用各种功能么？

我周末试一下，明天晚上给你答复～

**Comment by OptimusV5** [comment]
> > 想请教下，如果不插独显，只用核显，能正常开机使用各种功能么？
> 
> 我周末试一下，明天晚上给你答复～

感动，先谢过～

**Comment by zhixiangyao** [comment]
> > > 想请教下，如果不插独显，只用核显，能正常开机使用各种功能么？
> > 
> > 
> > 我周末试一下，明天晚上给你答复～
> 
> 感动，先谢过～

还不行～ 刚试了= =开不了

**Comment by OptimusV5** [comment]
> > > > 想请教下，如果不插独显，只用核显，能正常开机使用各种功能么？
> > > 
> > > 
> > > 我周末试一下，明天晚上给你答复～
> > 
> > 
> > 感动，先谢过～
> 
> 还不行～ 刚试了= =开不了

好的，十分感谢
